# Generated by Django 5.2 on 2025-04-10 10:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('SIGNATURE', 'Signature-based'), ('ANOMALY', 'Anomaly-based'), ('ML', 'Machine learning-based')], max_length=20)),
                ('rule_details', models.TextField(help_text='JSON representation of rule parameters')),
                ('severity', models.IntegerField(default=1, help_text='1-5 scale, 5 being most severe')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model_type', models.CharField(choices=[('CLASSIFIER', 'Classifier'), ('ANOMALY', 'Anomaly Detector'), ('ENSEMBLE', 'Ensemble Model'), ('HIERARCHICAL', 'Hierarchical Model')], max_length=20)),
                ('model_path', models.CharField(max_length=255)),
                ('parameters', models.TextField(help_text='JSON representation of model parameters')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('packet_count', models.IntegerField()),
                ('byte_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.FloatField(help_text='Flow duration in seconds')),
                ('avg_packet_size', models.FloatField(blank=True, null=True)),
                ('flow_rate', models.FloatField(blank=True, help_text='Packets per second', null=True)),
                ('byte_rate', models.FloatField(blank=True, help_text='Bytes per second', null=True)),
                ('packet_data', models.TextField(blank=True, help_text='JSON representation of packet data', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('interface_type', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('is_monitoring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HierarchicalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('structure', models.TextField(help_text='JSON representation of hierarchical model structure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('modelss', models.ManyToManyField(related_name='hierarchical_models', to='ids.mlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='NEW', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score (0-1)')),
                ('details', models.TextField(blank=True, help_text='Additional alert details', null=True)),
                ('attack_category', models.CharField(blank=True, choices=[('RECON', 'Reconnaissance'), ('DOS', 'Denial of Service'), ('U2R', 'User to Root'), ('R2L', 'Remote to Local'), ('PROBE', 'Probing'), ('BACKDOOR', 'Backdoor'), ('SHELLCODE', 'Shellcode'), ('WORM', 'Worm'), ('GENERIC', 'Generic'), ('ANALYSIS', 'Analysis'), ('FUZZERS', 'Fuzzers'), ('EXPLOIT', 'Exploit'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('attack_subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ids.detectionrule')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ids.networkflow')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('dataset_info', models.TextField(help_text='JSON representation of dataset information')),
                ('training_parameters', models.TextField(help_text='JSON representation of training parameters')),
                ('results', models.TextField(blank=True, help_text='JSON representation of training results', null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='ids.mlmodel')),
            ],
        ),
    ]
