# Generated by Django 5.2.4 on 2025-07-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Qoida nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('attack_types', models.JSONField(default=list, verbose_name='Hujum turlari')),
                ('min_severity_score', models.FloatField(default=0.7, verbose_name='Minimal jiddiylik bahosi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Ogohlantirish qoidasi',
                'verbose_name_plural': 'Ogohlantirish qoidalari',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('severity', models.CharField(choices=[('low', 'Kam'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Kritik')], default='medium', max_length=20, verbose_name='Jiddiylik darajasi')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('acknowledged', 'Qabul qilingan'), ('resolved', 'Hal qilingan'), ('false_positive', "Noto'g'ri signal")], default='open', max_length=20, verbose_name='Holat')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Manba IP')),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Maqsad IP')),
                ('attack_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hujum turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqt')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('network_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ids.networkflow', verbose_name='Tarmoq oqimi')),
            ],
            options={
                'verbose_name': 'Ogohlantirish',
                'verbose_name_plural': 'Ogohlantirishlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
